name: Publish package to GitHub Packages
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Import GPG key
        run: |
          echo "$GPG_SECRET_KEY" | base64 --decode | gpg --batch --yes --import
          KEY_ID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d: -f5)
          echo "default-key $KEY_ID" >> ~/.gnupg/gpg.conf
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}

      - name: Publish package
        run: mvn --batch-mode deploy -Prelease -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}